# Generated by Django 3.2 on 2021-10-19 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 5, 28, 31, 657404, tzinfo=utc)),
        ),
    ]
