# Generated by Django 3.2 on 2021-10-20 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_person_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 57, 24, 603316, tzinfo=utc)),
        ),
    ]
