# Generated by Django 3.2 on 2021-10-20 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_person_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 15, 23, 7, 800368, tzinfo=utc)),
        ),
    ]
