# Generated by Django 3.2 on 2021-10-24 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_person_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 5, 18, 27, 282435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
