# Generated by Django 3.2 on 2021-10-28 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20211024_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 13, 26, 30, 157471, tzinfo=utc)),
        ),
    ]
