# Generated by Django 3.2.8 on 2021-10-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='description',
        ),
    ]
