# Generated by Django 3.2 on 2021-10-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_remove_additionalinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='file',
        ),
    ]
